#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrich BTC proxy backtest rows with actual Polymarket Gamma/CLOB history where available.

Input: backtest_reports/backtest_trades.csv generated by backtest.py.
For each simulated signal, it finds the corresponding btc-updown-5m-{window_ts} market,
gets the relevant UP/DOWN token id, retrieves /prices-history near the entry timestamp,
and calculates PnL using the historical token price.

This is slower than BTC proxy backtesting because it uses one short-lived Polymarket
market per 5-minute window. Use it on recent days/weeks first, not multi-year ranges.
"""

import argparse
import csv
import json
import os
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Dict, List, Optional

POLY_GAMMA = os.getenv("POLYMARKET_GAMMA", "https://gamma-api.polymarket.com")
POLY_CLOB = os.getenv("POLYMARKET_HOST", "https://clob.polymarket.com")
FEE_RATE = float(os.getenv("CRYPTO_TAKER_FEE_RATE", "0.07"))


def http_json(url: str, params: Optional[dict] = None, timeout: int = 20):
    if params:
        url = url + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": "btc-bot-polymarket-replay/10.0"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8"))


def loads_list(v):
    if isinstance(v, list):
        return v
    if not v:
        return []
    try:
        return json.loads(v)
    except Exception:
        return []


def safe_float(v, default=None):
    try:
        if v is None or v == "":
            return default
        return float(str(v).replace(",", ""))
    except Exception:
        return default


def parse_price_to_beat(text: str) -> Optional[float]:
    patterns = [
        r"Price\s+to\s+Beat[:\s$]*([0-9][0-9,]*(?:\.\d+)?)",
        r"starting\s+price[:\s$]*([0-9][0-9,]*(?:\.\d+)?)",
        r"start\s+price[:\s$]*([0-9][0-9,]*(?:\.\d+)?)",
    ]
    for pat in patterns:
        m = re.search(pat, text or "", re.I)
        if m:
            return safe_float(m.group(1))
    return None


def parse_market(m: dict) -> dict:
    tokens = m.get("tokens") or []
    outcomes = loads_list(m.get("outcomes"))
    outcome_prices = loads_list(m.get("outcomePrices"))
    clob_ids = loads_list(m.get("clobTokenIds"))
    up_token = next((t for t in tokens if str(t.get("outcome", "")).lower() in {"up", "yes"}), None)
    down_token = next((t for t in tokens if str(t.get("outcome", "")).lower() in {"down", "no"}), None)
    if (not up_token or not down_token) and len(clob_ids) >= 2:
        mapped = {}
        if outcomes and len(outcomes) == len(clob_ids):
            for outcome, token_id in zip(outcomes, clob_ids):
                low = str(outcome).strip().lower()
                if low in {"up", "yes"}:
                    mapped["up"] = token_id
                elif low in {"down", "no"}:
                    mapped["down"] = token_id
        up_token = up_token or ({"token_id": mapped.get("up"), "outcome": "Up"} if mapped.get("up") else None)
        down_token = down_token or ({"token_id": mapped.get("down"), "outcome": "Down"} if mapped.get("down") else None)
        if (not up_token or not down_token) and not outcomes:
            up_token = up_token or {"token_id": clob_ids[0], "outcome": "Up"}
            down_token = down_token or {"token_id": clob_ids[1], "outcome": "Down"}
    price_map = {}
    if outcomes and outcome_prices and len(outcomes) == len(outcome_prices):
        for o, p in zip(outcomes, outcome_prices):
            price_map[str(o).lower()] = safe_float(p)
    text_blob = "\n".join(str(m.get(k, "")) for k in ["question", "title", "description", "resolutionSource", "rules", "umaResolutionData"])
    resolved = None
    for key in ("winningOutcome", "winning_outcome", "winner", "resolvedOutcome", "resolved_outcome", "result", "resolution", "outcome"):
        val = m.get(key)
        if val is None:
            continue
        low = str(val).strip().lower()
        if low in {"up", "yes"}:
            resolved = "UP"
        if low in {"down", "no"}:
            resolved = "DOWN"
    if resolved is None:
        up_p = price_map.get("up", price_map.get("yes"))
        down_p = price_map.get("down", price_map.get("no"))
        if up_p is not None and up_p >= 0.99:
            resolved = "UP"
        if down_p is not None and down_p >= 0.99:
            resolved = "DOWN"
    return {
        "slug": m.get("slug"),
        "condition_id": m.get("conditionId") or m.get("condition_id"),
        "up_token_id": (up_token or {}).get("token_id"),
        "down_token_id": (down_token or {}).get("token_id"),
        "price_to_beat": safe_float(m.get("priceToBeat")) or parse_price_to_beat(text_blob),
        "resolved_outcome": resolved,
        "rules_chainlink_ok": ("chainlink" in text_blob.lower() and "btc" in text_blob.lower()),
    }


def fetch_market(window_ts: int, cache_dir: Path) -> Optional[dict]:
    slug = f"btc-updown-5m-{int(window_ts)}"
    cache = cache_dir / "markets" / f"{slug}.json"
    cache.parent.mkdir(parents=True, exist_ok=True)
    if cache.exists():
        raw = json.loads(cache.read_text())
    else:
        data = http_json(f"{POLY_GAMMA}/markets", {"slug": slug}, timeout=20)
        markets = data if isinstance(data, list) else data.get("data", [])
        if not markets:
            return None
        raw = markets[0]
        cache.write_text(json.dumps(raw, ensure_ascii=False))
        time.sleep(0.03)
    return parse_market(raw)


def fetch_price_history(token_id: str, entry_ts: int, cache_dir: Path) -> List[dict]:
    cache = cache_dir / "prices" / f"{token_id}-{entry_ts}.json"
    cache.parent.mkdir(parents=True, exist_ok=True)
    if cache.exists():
        data = json.loads(cache.read_text())
    else:
        data = http_json(f"{POLY_CLOB}/prices-history", {
            "market": token_id,
            "startTs": int(entry_ts) - 300,
            "endTs": int(entry_ts) + 60,
            "interval": "1m",
            "fidelity": 1,
        }, timeout=20)
        cache.write_text(json.dumps(data, ensure_ascii=False))
        time.sleep(0.03)
    hist = data.get("history", data if isinstance(data, list) else []) or []
    return hist


def nearest_price(history: List[dict], entry_ts: int) -> Optional[float]:
    candidates = []
    for h in history:
        t = int(float(h.get("t", 0)))
        p = safe_float(h.get("p"))
        if p is None:
            continue
        # Prefer last known price at or before entry; allow nearest within 90 sec.
        candidates.append((abs(t - entry_ts), t <= entry_ts, t, p))
    if not candidates:
        return None
    before = [x for x in candidates if x[1]]
    if before:
        before.sort(key=lambda x: x[2], reverse=True)
        if abs(before[0][2] - entry_ts) <= 180:
            return before[0][3]
    candidates.sort(key=lambda x: x[0])
    return candidates[0][3] if candidates[0][0] <= 90 else None


def fee_per_share(price: float) -> float:
    price = max(0.0, min(1.0, price))
    return FEE_RATE * price * (1.0 - price)


def replay_rows(input_csv: Path, output_csv: Path, cache_dir: Path, limit: int = 0) -> dict:
    rows = list(csv.DictReader(input_csv.open()))
    if limit:
        rows = rows[:limit]
    out = []
    stats = {"input_rows": len(rows), "matched_markets": 0, "priced_rows": 0, "wins": 0, "pnl_per_share_sum": 0.0}
    for i, r in enumerate(rows, 1):
        window_ts = int(float(r["window_ts"]))
        entry_ts = int(float(r["entry_ts"]))
        direction = str(r["direction"]).upper()
        try:
            market = fetch_market(window_ts, cache_dir)
        except Exception as e:
            market = None
            r["replay_error"] = f"market_fetch_failed:{e}"
        if not market:
            r["replay_status"] = "market_missing"
            out.append(r)
            continue
        stats["matched_markets"] += 1
        token_id = market.get("up_token_id") if direction == "UP" else market.get("down_token_id")
        r.update({
            "pm_slug": market.get("slug"),
            "pm_token_id": token_id or "",
            "pm_price_to_beat": market.get("price_to_beat") or "",
            "pm_resolved_outcome": market.get("resolved_outcome") or "",
            "pm_rules_chainlink_ok": market.get("rules_chainlink_ok"),
        })
        if not token_id:
            r["replay_status"] = "token_missing"
            out.append(r)
            continue
        try:
            hist = fetch_price_history(token_id, entry_ts, cache_dir)
            entry_price = nearest_price(hist, entry_ts)
        except Exception as e:
            entry_price = None
            r["replay_error"] = f"price_fetch_failed:{e}"
        if entry_price is None:
            r["replay_status"] = "price_missing"
            out.append(r)
            continue
        outcome = market.get("resolved_outcome") or str(r.get("outcome", "")).upper()
        win = int(direction == outcome)
        pnl = (1.0 if win else 0.0) - entry_price - fee_per_share(entry_price)
        r.update({
            "replay_status": "priced",
            "pm_entry_price": entry_price,
            "pm_fee_per_share": fee_per_share(entry_price),
            "pm_outcome_used": outcome,
            "pm_win": win,
            "pm_pnl_per_share": pnl,
        })
        stats["priced_rows"] += 1
        stats["wins"] += win
        stats["pnl_per_share_sum"] += pnl
        out.append(r)
        if i % 50 == 0:
            print(f"replayed {i}/{len(rows)} rows")
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = sorted({k for row in out for k in row.keys()})
    with output_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for row in out:
            w.writerow(row)
    stats["win_rate_priced"] = stats["wins"] / stats["priced_rows"] if stats["priced_rows"] else 0.0
    stats["avg_pnl_per_share_priced"] = stats["pnl_per_share_sum"] / stats["priced_rows"] if stats["priced_rows"] else None
    return stats


def main():
    ap = argparse.ArgumentParser(description="Replay proxy backtest rows with actual Polymarket CLOB price-history")
    ap.add_argument("--input", default="backtest_reports/backtest_trades.csv")
    ap.add_argument("--output", default="backtest_reports/polymarket_replay_trades.csv")
    ap.add_argument("--cache-dir", default="backtest_cache/polymarket")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()
    stats = replay_rows(Path(args.input), Path(args.output), Path(args.cache_dir), args.limit)
    Path(args.output).with_suffix(".summary.json").write_text(json.dumps(stats, indent=2, ensure_ascii=False))
    print(json.dumps(stats, indent=2, ensure_ascii=False))
    print("Output:", args.output)


if __name__ == "__main__":
    main()
